[project]
name = 'OTC-city-jing'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.fair]
path = 'contracts/fair.clar'
clarity_version = 2
epoch = 2.5

[contracts.send-many-memo]
path = 'contracts/send-many-memo.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.5

[contracts.simJing]
path = 'contracts/deployed/batch-1/simJing.clar'
clarity_version = 2
epoch = 2.5

[contracts.simCash]
path = 'contracts/deployed/batch-1/simCash.clar'
clarity_version = 2
epoch = 2.5

[contracts.yang]
path = 'contracts/yang.clar'
clarity_version = 2
epoch = 2.5

[contracts.yin]
path = 'contracts/yin.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
